init: git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

skip_tags: true

install:
  - ps: Install-Product node 2
  - npm install --production
  - npm install require-bower-files tape
  - npm install -g bower
  - bower install

build: off

test_script: node test.js
